# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 05:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentat', models.DateTimeField()),
                ('code', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=255)),
                ('is_expired', models.BooleanField(default=True)),
                ('expiratin_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=3)),
                ('full_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreferncesTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefernce_type', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PrivatTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transactionstime', models.DateTimeField()),
                ('purpose', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pseudonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PublicTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transactionstime', models.DateTimeField()),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SitePrefernce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SitePreferncesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailisconfirmed', models.BooleanField(default=False)),
                ('birthdate', models.DateField(null=True)),
                ('regdate', models.DateTimeField()),
                ('famidconfirmed', models.BooleanField(default=False)),
                ('cellcountry', models.CharField(blank=True, max_length=255, null=True)),
                ('cellarea', models.CharField(blank=True, max_length=255, null=True)),
                ('cellnum', models.CharField(blank=True, max_length=255, null=True)),
                ('addrcountry', models.CharField(blank=True, max_length=255, null=True)),
                ('addrpostid', models.CharField(blank=True, max_length=255, null=True)),
                ('addrtown', models.CharField(blank=True, max_length=255, null=True)),
                ('addrstr', models.CharField(blank=True, max_length=255, null=True)),
                ('addrhousenum', models.CharField(blank=True, max_length=255, null=True)),
                ('addrapt', models.CharField(blank=True, max_length=255, null=True)),
                ('addradditional', models.CharField(blank=True, max_length=255, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Family')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_bool', models.NullBooleanField()),
                ('value_float', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('value_string', models.CharField(max_length=128, null=True)),
                ('value_int', models.IntegerField(null=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.SitePrefernce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Users')),
            ],
        ),
        migrations.AddField(
            model_name='siteprefernce',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.SitePreferncesList'),
        ),
        migrations.AddField(
            model_name='siteprefernce',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.PreferncesTypes'),
        ),
        migrations.AddField(
            model_name='publictransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Users'),
        ),
        migrations.AddField(
            model_name='pseudonym',
            name='for_the_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_user', to='budget.Users'),
        ),
        migrations.AddField(
            model_name='pseudonym',
            name='of_the_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of_user', to='budget.Users'),
        ),
        migrations.AddField(
            model_name='privattransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Users'),
        ),
        migrations.AddField(
            model_name='confirmationdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Users'),
        ),
    ]
