# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 15:55
from __future__ import unicode_literals

from django.db import migrations

def intiate_database(apps, schema_editor):
    fill_the_preference_types(apps, schema_editor)
    fill_the_site_prefernces_list(apps, schema_editor)
    connect_name_to_type(apps, schema_editor)
    
def connect_name_to_type(apps, schema_editor):    
    preference_type = apps.get_model("budget", "PreferncesTypes")
    settings_type = apps.get_model("budget", "SitePreferncesList")
    name_type_connection = apps.get_model("budget", "SitePrefernce")
    def_tab = settings_type.objects.get(setting_name="default_tab_is_public")
    bool_type = preference_type.objects.get(prefernce_type="bool")
    int_type = preference_type.objects.get(prefernce_type="int")
    new_connection1 = name_type_connection(setting = def_tab, type = bool_type)
    new_connection1.save()
    currency = settings_type.objects.get(setting_name="main_currency")
    new_connection2 = name_type_connection(setting = currency, \
                                           type = int_type)
    new_connection2.save()
    

def fill_the_preference_types(apps, schema_editor):
    preference_type = apps.get_model("budget", "PreferncesTypes")
    types_of_settings= ["string", "bool", "float", "int"]
    for this_type in types_of_settings:
        new_type=preference_type(prefernce_type=this_type)
        new_type.save()
        
def fill_the_site_prefernces_list(apps, schema_editor):
    settings_type = apps.get_model("budget", "SitePreferncesList")
    names_of_settings= ["default_tab_is_public", "main_currency"]
    for this_setting in names_of_settings:
        new_entry=settings_type(setting_name=this_setting)
        new_entry.save()
        
       


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
                  migrations.RunPython(intiate_database),
    ]