# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='short_name',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
