CREATE USER IF NOT EXISTS 'hk_admin'@'localhost' IDENTIFIED BY 'VCEXFVaYYYEP5njx';
CREATE USER IF NOT EXISTS 'hk_admin'@'%' IDENTIFIED BY 'VCEXFVaYYYEP5njx';
CREATE USER IF NOT EXISTS 'hk_admin'@'127.0.0.1' IDENTIFIED BY 'VCEXFVaYYYEP5njx';