# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20151223_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenceschange',
            name='field_changed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='preferenceschange',
            name='old_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionchange',
            name='old_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userchange',
            name='old_value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
